### ISSUE TITLE
Identity assertion for application services

### ISSUE THREAD

**Issue by Nauxuron** [ruma/ruma-client#27]
Application services need to be able to use the client-server API. They use their `as_token` as access token for authentication and they can add a `user_id` query parameter to act as a user in their namespace. See the [spec](https://matrix.org/docs/spec/application_service/r0.1.2#identity-assertion) for more details.

ruma-client needs to support:
- [ ] Specifying an access token without needing to login or register an account. Currently a session requires an associated user ID and device ID, which don't exist for application services.
- [ ] Specifying a `user_id` with every request, and appending that as a query parameter.

**Comment by jplatte** [comment]
Fixed by #36
