### ISSUE TITLE
End-to-End Encryption

### ISSUE THREAD

**Issue by stoically** [ruma/ruma-client#31]
Would be great to have E2EE support. A starting point might be the [official guide](https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide/) which utilizes [libolm](https://gitlab.matrix.org/matrix-org/olm).

@poljar started work on that already in https://github.com/poljar/nio-rust (nio-olm-rs and nio-olm-sys, License: MIT)

The [fractal client](https://gitlab.gnome.org/GNOME/fractal) started work on that as well, called [metaolm](https://gitlab.gnome.org/World/metaolm), which is a wrapper around [olm-rs](https://gitlab.gnome.org/jhaye/olm-rs), which is wrapper around [olm-sys](https://gitlab.gnome.org/BrainBlasted/olm-sys) (License: GPL).

**Comment by jplatte** [comment]
I'll close this for now. If somebody wants E2E support directly in Ruma (rather than through matrix-rust-sdk) in the future, please discuss in [#ruma:matrix.org](https://matrix.to/#/#ruma:matrix.org) first.
