### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by Geemili** [ruma/ruma-client#4]
The readme is a bit sparse. How far along is the project? What needs to be done? <https://www.ruma.io/> doesn't have any more detail.

Answers to these question would be a nice addition to the README.

**Comment by jimmycuadra** [comment]
Thanks for your interest and apologies for the lack of information in the README. ruma-client is currently a work in progress. Right now the main blockers on finishing it are:

* Converting ruma-client-api, which contains types for each API endpoint's request and response, to use the procedural macro from ruma-api-macros. This is roughly 1/3 done and I'm making progress on it.
* A final release of tokio-based hyper, which the community has been told is coming "soon" for like the last 6 months, so who knows.

**Comment by florianjacob** [comment]
Update from Jimmy, yesterday in #ruma:matrix.org:

> ruma-client is mostly as far done as it needs to be (might be missing a few APIs, I haven't looked at it in a long time) and is waiting on stabilizations of its dependencies […]. the other big thing […] is places where synapse doesn't actually follow the spec and so ruma-client won't work against a live synapse server as-is. the goal is to fix those things properly in synapse rather than have ruma-client go off spec.

Source: https://matrix.to/#/!wzHrsErnsyaqbpFiRQ:matrix.org/$15246419371107088KVHHl:matrix.org

**Comment by jplatte** [comment]
Assigning myself as I intend to update the README accordingly (hopefully soon).
